### ISSUE TITLE
Unable to obtain ACME certificate for domains

### ISSUE THREAD

**Issue by selukov** [heyvaldemar/rocketchat-traefik-letsencrypt-docker-compose#1]
Не выдает сертификат 
time="2022-01-13T09:21:35Z" level=error msg="Unable to obtain ACME certificate for domains \"selukov.website\": unable to generate a certificate for the domains [selukov.website]: error: one or more domains had a problem:\n[selukov.website] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Timeout during connect (likely firewall problem)\n" providerName=letsencrypt.acme routerName=rocketchat@docker rule="Host(`selukov.website`)"
time="2022-01-13T09:21:37Z" level=error msg="Unable to obtain ACME certificate for domains \"traefik.selukov.website\": unable to generate a certificate for the domains [traefik.selukov.website]: error: one or more domains had a problem:\n[traefik.selukov.website] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Timeout during connect (likely firewall problem)\n" routerName=dashboard@docker rule="Host(`traefik.selukov.website`)" providerName=letsencrypt.acme

вроде все открыто
└$► sudo nc -zv -w5 selukov.website 22 80 443 3000
Connection to selukov.website 22 port [tcp/ssh] succeeded!
Connection to selukov.website 80 port [tcp/http] succeeded!
Connection to selukov.website 443 port [tcp/https] succeeded!
nc: connect to selukov.website port 3000 (tcp) timed out: Operation now in progress
nc: connect to selukov.website port 3000 (tcp) failed: Network is unreachable

**Comment by heyvaldemar** [comment]
1. Попробуйте использовать Traefik 2.6.
`image: traefik:2.6`

2. Попробуйте отключить IPv6 на вашем сервере. Вот результат моей проверки:

`~ nc -vz selukov.website 443
nc: connectx to selukov.website port 443 (tcp) failed: Network is unreachable
Connection to selukov.website port 443 [tcp/https] succeeded!`

`~ nc -vz selukov.website 80
nc: connectx to selukov.website port 80 (tcp) failed: Network is unreachable
Connection to selukov.website port 80 [tcp/http] succeeded!`


**Если у вас есть вопросы по ИТ, то можете задавать их в чате:**

🚀 Чат с ИТ-специалистами в [Telegram](https://bit.ly/heyvaldemar-chat-telegram-ru).

👾 Чат с ИТ-специалистами в [Discord](https://bit.ly/heyvaldemar-chat-discord-ru).

**Comment by selukov** [comment]
acme-tls почему-то не хочет давать сертификат 
https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/
исправил на acme-http
https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/
```code
        #- "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # Email for Let's Encrypt (replace with yours)
      - "--log.level=DEBUG"
      - "--certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
```

**Comment by heyvaldemar** [comment]
Привет @selukov, с `acme-http` заработало?

**Comment by selukov** [comment]
> Привет @selukov, с `acme-http` заработало?

да, уже несколько раз удалял сертификаты, docker volume rm rocketchat_traefik-certificates, с acme-http работает постоянно, acme-tls еще ни разу не дал даже тестовый сертификат

**Comment by selukov** [comment]
> 1. Попробуйте использовать Traefik 2.6.
>        `image: traefik:2.6`
> 
>     2. Попробуйте отключить IPv6 на вашем сервере. Вот результат моей проверки:
> 
> 
> `~ nc -vz selukov.website 443 nc: connectx to selukov.website port 443 (tcp) failed: Network is unreachable Connection to selukov.website port 443 [tcp/https] succeeded!`
> 
> `~ nc -vz selukov.website 80 nc: connectx to selukov.website port 80 (tcp) failed: Network is unreachable Connection to selukov.website port 80 [tcp/http] succeeded!`
> 
> **Если у вас есть вопросы по ИТ, то можете задавать их в чате:**
> 
> rocket Чат с ИТ-специалистами в [Telegram](https://bit.ly/heyvaldemar-chat-telegram-ru).
> 
> space_invader Чат с ИТ-специалистами в [Discord](https://bit.ly/heyvaldemar-chat-discord-ru).

Я вот думаю могло acme-tls не работать вследствии неверного reverse proxy
dig +noall +answer -x 194.233.161.248
248.161.233.194.in-addr.arpa. 86400 IN	PTR	194-233-161-248.ip.linodeusercontent.com.

проверю как примениться корректный selukov.website
