### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by inn0minatus** [heyvaldemar/rocketchat-traefik-letsencrypt-docker-compose#3]
Not able to run. Service stated as unhealthy, despite the SERVER RUNNING status in logs. Also log prints next error:

```
rocketchat-rocketchat-1  | Exception in callback of async function: errorClass [Error]: [You must set "intervalTimeInMS" property in rateLimiter for REST API endpoint]
rocketchat-rocketchat-1  |     at APIClass.addRateLimiterRuleForRoutes (app/api/server/api.js:266:10)
rocketchat-rocketchat-1  |     at app/api/server/api.js:251:10
rocketchat-rocketchat-1  |     at Array.forEach (<anonymous>)
rocketchat-rocketchat-1  |     at APIClass.reloadRoutesToRefreshRateLimiter (app/api/server/api.js:249:16)
rocketchat-rocketchat-1  |     at app/api/server/api.js:852:9
rocketchat-rocketchat-1  |     at runWithEnvironment (packages/meteor.js:1320:24)
rocketchat-rocketchat-1  |     at packages/meteor.js:1333:14
rocketchat-rocketchat-1  |     at runWithEnvironment (packages/meteor.js:1320:24) {
rocketchat-rocketchat-1  |   isClientSafe: true,
rocketchat-rocketchat-1  |   error: 'You must set "intervalTimeInMS" property in rateLimiter for REST API endpoint',
rocketchat-rocketchat-1  |   reason: undefined,
rocketchat-rocketchat-1  |   details: undefined,
rocketchat-rocketchat-1  |   errorType: 'Meteor.Error'
rocketchat-rocketchat-1  | }
```

Docker version 23.0.1
Docker Compose version 2.16.0

**Comment by heyvaldemar** [comment]
hey, it seems you do not have enough RAM to run Rocket.Chat.

You can check the requirements on the [official website](https://docs.rocket.chat/deploy/prepare-for-your-deployment/hardware-requirements).

**I just deployed it, and it works perfectly fine.**

We can discuss it in the Russian-speaking communities on [Telegram](https://t.me/DevOpsCompass) or [Discord](https://discord.gg/HBTF9N5TKH). It'll be more convenient.

**Comment by inn0minatus** [comment]
RAM shouldn't be an issue, I have 32GB on the machine I'm testing on.

**Comment by heyvaldemar** [comment]
I have it running now.

![1](https://user-images.githubusercontent.com/10498744/220403164-a85511a6-fb57-4a64-8562-b3010fdedafb.jpg)

If you have questions about installation or configuration, then ask me and other IT experts in our Russian-speaking community on [Telegram](https://t.me/DevOpsCompass) or [Discord](https://discord.gg/HBTF9N5TKH).
